#!/usr/bin/env python3
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
try:
    import routes.cli  # noqa: F401
except ImportError:
    pass
from framework.Console.ConsoleKernel import handle_console
if __name__ == "__main__":
    exit(handle_console(sys.argv[1:]))